---

# Setup docker



# Setup the Jenkins server

- name: Create a directory if it does not exist
  file:
    path: /var/lib/jenkins
    state: directory
    mode: '0755'
    owner: 1000

- name: Setup the Jenkins container
  docker_container:
    name: sectools-jenkins
    image: jenkins/jenkins:lts
    state: started
    recreate: yes
    published_ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins /var/lib/jenkins