---

- name: Update cache
  apt:
    update_cache: yes

- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
      - containerd 
      - runc
      - docker.io
      - vim
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python3-pip
    state: present

- name: Add Docker apt key.
  apt_key:
    url: "{{ jenkins_docker_apt_gpg }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key


- name: Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key is failed

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: >
    curl -sSL {{ jenkins_docker_apt_gpg }} | sudo apt-key add -
  args:
    warn: false
  when: add_repository_key is failed

- name: Add Docker repository.
  apt_repository:
    repo: "{{ jenkins_docker_apt_repository }}"
    state: present
    update_cache: true  

- name: Install Docker.
  package:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
  notify: restart docker

- name: Ensure docker library is installed.
  pip:
    name: docker