---
# tasks file for sectools-ansible-jenkins

- name: Create a jenkins directory if it does not exist
  file:
    path: /var/lib/jenkins
    state: directory
    mode: '0755'

# Install through package manager

- name: Install Docker package
  package:
    name: "{{ docker_package }}"
    state: present 
  notify: "docker_service"

- name: Enable and start service cylancesvc
  service:
    name: docker 
    enabled: yes
